#pragma once
#include "FreeImage.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>




#define STF(x) { x , #x },

// literal string to format value
struct _t_stfif {
  FREE_IMAGE_FORMAT fif;
  char* s;
} stfif_list[] = {
STF(FIF_UNKNOWN)
STF(FIF_BMP)
STF(FIF_ICO)
STF(FIF_JPEG)
STF(FIF_JNG)
STF(FIF_KOALA)
STF(FIF_LBM)
STF(FIF_IFF)
STF(FIF_MNG)
STF(FIF_PBM)
STF(FIF_PBMRAW)
STF(FIF_PCD)
STF(FIF_PCX)
STF(FIF_PGM)
STF(FIF_PGMRAW)
STF(FIF_PNG)
STF(FIF_PPM)
STF(FIF_PPMRAW)
STF(FIF_RAS)
STF(FIF_TARGA)
STF(FIF_TIFF)
STF(FIF_WBMP)
STF(FIF_PSD)
STF(FIF_CUT)
STF(FIF_XBM)
STF(FIF_XPM)
STF(FIF_DDS)
STF(FIF_GIF)
STF(FIF_HDR)
STF(FIF_FAXG3)
STF(FIF_SGI)
STF(FIF_EXR)
STF(FIF_J2K)
STF(FIF_JP2)
STF(FIF_PFM)
STF(FIF_PICT)
STF(FIF_RAW)
STF(FIF_WEBP)
STF(FIF_JXR)
};
// literal string to flag value
struct _t_stf {
  int flag;
  char* s;
} stf_list[] = {
STF(BMP_DEFAULT)
STF(BMP_SAVE_RLE)
STF(EXR_DEFAULT)
STF(EXR_FLOAT)
STF(EXR_NONE)
STF(EXR_ZIP)
STF(EXR_PIZ)
STF(EXR_PXR24)
STF(EXR_B44)
STF(EXR_LC)
STF(J2K_DEFAULT)
STF(JP2_DEFAULT)
STF(PNG_DEFAULT)
STF(PNG_Z_BEST_SPEED)
STF(PNG_Z_DEFAULT_COMPRESSION)
STF(PNG_Z_BEST_COMPRESSION)
STF(PNG_Z_NO_COMPRESSION)
STF(PNG_INTERLACED)
STF(WEBP_DEFAULT)
STF(WEBP_LOSSLESS)
STF(JPEG_DEFAULT)
STF(JPEG_QUALITYSUPERB)
STF(JPEG_QUALITYGOOD)
STF(JPEG_QUALITYNORMAL)
STF(JPEG_QUALITYAVERAGE)
STF(JPEG_QUALITYBAD)
STF(JPEG_PROGRESSIVE)
STF(JPEG_SUBSAMPLING_411)
STF(JPEG_SUBSAMPLING_420)
STF(JPEG_SUBSAMPLING_422)
STF(JPEG_SUBSAMPLING_444)
STF(JPEG_OPTIMIZE)
STF(JPEG_BASELINE)
STF(ICO_DEFAULT)
STF(ICO_MAKEALPHA)
STF(JXR_DEFAULT)
STF(JXR_LOSSLESS)
STF(JXR_PROGRESSIVE)
STF(PNM_DEFAULT)
STF(PNM_SAVE_RAW)
STF(PNM_SAVE_ASCII)
STF(TIFF_DEFAULT)
STF(TIFF_CMYK)
STF(TIFF_PACKBITS)
STF(TIFF_DEFLATE)
STF(TIFF_ADOBE_DEFLATE)
STF(TIFF_NONE)
STF(TIFF_CCITTFAX3)
STF(TIFF_CCITTFAX4)
STF(TIFF_LZW)
STF(TIFF_JPEG)
STF(TIFF_LOGLUV)
STF(TARGA_DEFAULT)
STF(TARGA_SAVE_RLE)
};
#undef STF
int stfif_list_len = sizeof(stfif_list) / sizeof(struct _t_stfif);
int stf_list_len = sizeof(stf_list) / sizeof(struct _t_stf);



// color type to string
struct _t_cts {
  FREE_IMAGE_COLOR_TYPE ct;
  char* s;
} cts_list[]  = {
  {FIC_MINISWHITE, "Monochrome White First"},
  {FIC_MINISBLACK, "Monochrome Black First"},
  {FIC_RGB, "RGB"},
  {FIC_PALETTE, "Palettized"},
  {FIC_RGBALPHA, "RGBA"},
  {FIC_CMYK, "CMYK"},
};
int cts_list_len = sizeof(cts_list) / sizeof(struct _t_cts);
